WebBooks/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('catalog.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls'))
]

catalog/urls.py
from django.urls import path, re_path
from . import views

urlpatterns = [
    path('', views.index, name="index"),
    re_path(r"^books/$", views.BookListView.as_view(), name="books"),
    re_path(r"^book/(?P<pk>\d+)$",
            views.BookDetailView.as_view(), name="book-detail"),
    re_path(r"^authors/$", views.AuthorListView.as_view(),
            name="authors"),
    re_path(r"^mybooks/$", views.LoanedBooksByUserListView.as_view(),
            name="my-borrowed"),
]

catalog/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from datetime import date

# Create your models here.


class Genre(models.Model):
    name = models.CharField(
        max_length=200, help_text='Введите жанр книги',
        verbose_name='Жанр книги')

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('name',)
        verbose_name = 'Жанр'
        verbose_name_plural = 'Жанры'


class Language(models.Model):
    name = models.CharField(
        max_length=200, verbose_name='Язык книги')

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('name',)
        verbose_name = 'Язык'
        verbose_name_plural = 'Языки'            


class Author(models.Model):
    first_name = models.CharField(max_length=200, verbose_name='Имя автора')
    last_name = models.CharField(max_length=200, verbose_name='Фамилия автора')
    date_of_birth = models.DateField(
        verbose_name='Дата рождения', null=True, blank=True)
    date_of_death = models.DateField(
        verbose_name='Дата смерти', null=True, blank=True)

    def __str__(self):
        return f"{self.last_name} {self.first_name}"

    class Meta:
        ordering = ('last_name', 'first_name')
        verbose_name = 'Автор'
        verbose_name_plural = 'Авторы'        


class Book(models.Model):
    title = models.CharField(max_length=255, verbose_name="Название книги")
    genre = models.ForeignKey(
        'Genre', on_delete=models.CASCADE, verbose_name='Жанр книги',
        null=True)
    language = models.ForeignKey(
        'Language', on_delete=models.CASCADE, verbose_name='Язык книги',
        null=True)
    author = models.ManyToManyField(
        'Author', verbose_name='Автор книги')
    summary = models.TextField(
        max_length=1000, verbose_name='Аннотация книги')
    isbn = models.CharField(
        max_length=13, verbose_name="ISBN",
        help_text='Должно содержать 13 символов')
    
    def __str__(self):
        return self.title        

    def get_absolute_url(self):
        # return f"books/{self.id}"
        return reverse('book-detail', args=[str(self.id)])

    def display_author(self):
        return ', '.join([author.last_name for author in self.author.all()])
    display_author.short_description = 'Авторы'

    class Meta:
        ordering = ('title',)
        verbose_name = 'Книга'
        verbose_name_plural = 'Книги'        


class Status(models.Model):
    name = models.CharField(
        max_length=20, verbose_name='Статус экземпляра книги')

    def __str__(self):
        return self.name


    class Meta:
        ordering = ('name',)
        verbose_name = 'Статус'
        verbose_name_plural = 'Статусы'    


class BookInstance(models.Model):
    book = models.ForeignKey('Book', on_delete=models.CASCADE, null=True)
    inv_nom = models.CharField(max_length=20, verbose_name="Инвентарный номер")
    imprint = models.CharField(max_length=200, verbose_name="Издательство")
    status = models.ForeignKey(
        'Status', on_delete=models.CASCADE, null=True,
        verbose_name='Статус экземпляра книги')
    due_back = models.DateField(
        null=True, blank=True, verbose_name='Срок сдачи')
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True,
                                 blank=True, verbose_name="Заказчик",
                                 help_text="Выберите заказчика книги")

    def __str__(self):
        return f"{self.inv_nom} {self.book} {self.status}"

    def get_status_display(self):
        return self.status

    class Meta:
        ordering = ('inv_nom',)
        verbose_name = 'Экземпляр книги'
        verbose_name_plural = 'Экземпляры книги'

    @property
    def is_overdue(self):
        return self.due_back and date.today() > self.due_back

class Link(models.Model):
    book_a = models.ForeignKey('Book', on_delete=models.CASCADE, null=True)
    link = models.URLField('Ссылка', max_length=255)

    def __str__(self):
        return self.link

    class Meta:
        ordering = ('link',)
        verbose_name = 'Ссылка на книгу в других магазинах'
        verbose_name_plural = 'Ссылки на книгу в других магазинах'

catalog/views.py
from django.shortcuts import render
from django.views import generic
from .models import Book, Author, BookInstance, Genre, Link
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.


def index(request):
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()
    num_instances_available = BookInstance.objects.filter(
        status__exact=2).count()
    num_authors = Author.objects.count()
    num_visits = request.session.get('num_visits', 1)
    request.session['num_visits'] = num_visits + 1
    return render(request, 'index.html', context={
        'num_books': num_books,
        'num_instances': num_instances,
        'num_instances_available': num_instances_available,
        'num_authors': num_authors,
        'num_visits': num_visits
    })


class BookListView(generic.ListView):
    model = Book
    paginate_by = 10


class BookDetailView(generic.DetailView):
    model = Book


class AuthorListView(generic.ListView):
    model = Author
    paginate_by = 10

class Linkline(generic.ListView):
    model = Link


class LoanedBooksByUserListView(LoginRequiredMixin, generic.ListView):
    model = BookInstance
    template_name = 'catalog/book_instance_list_borrowed_user.html'
    paginate_by = 10

    def get_queryset(self):
        return BookInstance.objects \
            .filter(borrower=self.request.user) \
            .filter(status__exact='7') \
            .order_by('due_back')

catalog/templates/base.html
{% load static %}
<html>

<head>
    <meta charset="utf-8">
    <title>WebBooks</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
        crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{%static 'css/main.css'%}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<body>
    <div class="col-lg-8 mx-auto p-4 py-md-5">
        <header class="d-flex align-items-center pb-3 mb-5 border-bottom">
            <a href="/" class="d-flex align-items-center text-dark text-decoration-none navbar-header">
                Каталог книг
            </a>
            <nav class="nav">
                <a href="{%url 'books'%}" class="nav-link">Книги</a>
                <a href="{%url 'authors'%}" class="nav-link">Авторы</a>
                {%if user.is_authenticated%}
                <a href="{%url 'my-borrowed'%}" class="nav-link">Мои заказы</a>
                {%endif%}
                
            </nav>
            <nav class="nav ms-auto">
                {%if user.is_authenticated%}
                <a class="nav-link disabled">{{user.get_username}}</a>
                <a href="{% url 'logout'%}?next={{request.path}}" class="nav-link">Выйти</a>
                {%else%}
                <a href="{% url 'login'%}?next={{request.path}}" class="nav-link">Войти</a>
                {%endif%}
            </nav>
        </header>
        <main>
            {%block content%}
            {%endblock%}
            {%block pagination%}
            {%if is_paginated%}
            <ul class="pagination">
                {%if page_obj.has_previous%}
                <li class="page-item">
                    <a href="{{request.path}}?page={{page_obj.previous_page_number}}" class="page-link">
                        Предыдущая
                    </a>
                </li>
                {%endif%}
                <li class="page-item disabled">
                    <a class="page-link">
                        {{page_obj.number}}/{{page_obj.paginator.num_pages}}
                    </a>
                </li>
                {%if page_obj.has_next%}
                <li class="page-item">
                    <a href="{{request.path}}?page={{page_obj.next_page_number}}" class="page-link">
                        Следующая
                    </a>
                </li>
                {%endif%}

            </ul>
            {%endif%}
            {%endblock%}
        </main>
        <footer>
            НИЯУ МИФИ &middot; &copy; 2022
        </footer>
    </div>
</body>

</html>

catalog/templates/catalog/author_list.html
{%extends "base.html"%}

{%block content%}
<h1>Список авторов</h1>

  {%if author_list%}
    <ul>
      {% for author in author_list %}
      <p>
        {{author.last_name}} {{author.first_name}}
        <b>
          Родился—
          {{author.date_of_birth}}
        </b>
        <b>
          Умер—
          {{author.date_of_death}}
        </b>
      </p>
      {% endfor %}
    </ul>
  {%else%}
    <p>В базе данных нет авторов</p>
  {%endif%}
{%endblock%}

catalog/templates/catalog/book_detail.html
{%extends 'base.html'%}

{% block content %}
<h1>{{book.title}}</h1>
  {% for author in book.author.all  %}
    <p>
      <b>Автор:</b>
      {{author.last_name}} {{author.first_name}}
    </p>
  {% endfor %}
  {{book.bookinstance_set.count}}
  {% for l in book.link_set.all %}
  <ul>
  <a href="{{l.link}}">Книга в другом магазине</a>
  </ul>
  {% endfor %}
  {% for copy in book.bookinstance_set.all %}
  <p class="{% if copy.status.id == 1%} text-success
  {%elif copy.status.id == 2%} text-danger
  {%else%} text-warning
  {%endif%}">
  {{copy.status.id}}
  {{copy.get_status_display}}
  </p>

  {% endfor %}
{% endblock  %}

catalog/templates/catalog/book_instance_list_borrowed_user.html
{% extends "base.html"%}

{%block content%}
<h1>Взятые книги</h1>
{%if bookinstance_list%}
<ul>
  {%for bookinst in bookinstance_list%}
  <li class="{%if bookinst.is_overdue%}text-danger{%endif%}">
    <a href="{%url 'book-detail' bookinst.book.pk%}">
      {{bookinst.book.title}}
    </a>
    ({{bookinst.due_back}})
  </li>
  {%endfor%}
</ul>
{%else%}
<div class="alert alert-info">
  Нет книг со статусом
  <b class="text-uppercase">в заказе</b>
</div>
{%endif%}
{%endblock%}

catalog/templates/catalog/book_list.html
{%extends "base.html"%}

{%block content%}
<h1>Список книг</h1>

  {%if book_list%}
    <ul>
      {% for book in book_list %}
      <li>
        <a href="{{book.get_absolute_url}}">
          {{book.title}}
        </a>  
        {{book.genre}}
      </li>
      {% endfor %}
    </ul>
  {%else%}
    <p>В базе данных нет книг</p>
  {%endif%}
{%endblock%}

catalog/templates/index.html
{%extends "base.html"%}
{%block content%}
<h1>Главная страница</h1>
<ul>
  <li>
    <b>Количество книг:</b>
    {{num_books}}
  </li>
  <li>
    <b>Количество экземпляров книг:</b>
    {{num_instances}}
  </li>
  <li>
    <b>Количество авторов:</b>
    {{num_authors}}
  </li>
</ul>
<p>
  Количество посещений данной страницы:
  {{num_visits}}
</p>
{%endblock%}